/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doktergigi;

/**
 *
 * @author ASUS
 */
public class FPengaturan extends javax.swing.JFrame {

    /**
     * Creates new form FPengaturan
     */
    public FPengaturan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LAdmin = new javax.swing.JLabel();
        btHome = new javax.swing.JButton();
        btData = new javax.swing.JButton();
        btPasien = new javax.swing.JButton();
        btInformasi = new javax.swing.JButton();
        btSetting = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        btTambah = new javax.swing.JButton();
        btinformasi2 = new javax.swing.JButton();
        btTentang = new javax.swing.JButton();
        btReferensi = new javax.swing.JButton();
        LPengaturan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LAdmin.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LAdmin.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 330, 40));

        btHome.setBorderPainted(false);
        btHome.setContentAreaFilled(false);
        btHome.setFocusPainted(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 30, 20));

        btData.setBorderPainted(false);
        btData.setContentAreaFilled(false);
        btData.setFocusPainted(false);
        btData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataActionPerformed(evt);
            }
        });
        getContentPane().add(btData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 30, 30));

        btPasien.setBorderPainted(false);
        btPasien.setContentAreaFilled(false);
        btPasien.setFocusPainted(false);
        btPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 20, 20));

        btInformasi.setBorderPainted(false);
        btInformasi.setContentAreaFilled(false);
        btInformasi.setFocusPainted(false);
        btInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasiActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 20, 20));

        btSetting.setBorderPainted(false);
        btSetting.setContentAreaFilled(false);
        btSetting.setFocusPainted(false);
        btSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingActionPerformed(evt);
            }
        });
        getContentPane().add(btSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 30, 30));

        btKeluar.setBorderPainted(false);
        btKeluar.setContentAreaFilled(false);
        btKeluar.setFocusPainted(false);
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 30, 30));

        btTambah.setBorderPainted(false);
        btTambah.setContentAreaFilled(false);
        btTambah.setFocusPainted(false);
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 130, 20));

        btinformasi2.setBorderPainted(false);
        btinformasi2.setContentAreaFilled(false);
        btinformasi2.setFocusPainted(false);
        btinformasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btinformasi2ActionPerformed(evt);
            }
        });
        getContentPane().add(btinformasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 440, 20));

        btTentang.setBorderPainted(false);
        btTentang.setContentAreaFilled(false);
        btTentang.setFocusPainted(false);
        btTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTentangActionPerformed(evt);
            }
        });
        getContentPane().add(btTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 227, 440, 20));

        btReferensi.setBorderPainted(false);
        btReferensi.setContentAreaFilled(false);
        btReferensi.setFocusPainted(false);
        btReferensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReferensiActionPerformed(evt);
            }
        });
        getContentPane().add(btReferensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 440, 20));

        LPengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Fpengaturan.png"))); // NOI18N
        getContentPane().add(LPengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        jFrameDashboard jFrameDashboard = new jFrameDashboard();
        jFrameDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataActionPerformed
        // TODO add your handling code here:
        jFrameDataPasien jFrameDataPasien = new jFrameDataPasien();
        jFrameDataPasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDataActionPerformed

    private void btPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasienActionPerformed
        // TODO add your handling code here:
        jFramePasien jFramePasien = new jFramePasien();
        jFramePasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPasienActionPerformed

    private void btInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasiActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btInformasiActionPerformed

    private void btSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingActionPerformed
        // TODO add your handling code here:
        FPengaturan FPengaturan = new FPengaturan();
        FPengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSettingActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        FLogin FLogin = new FLogin();
        FLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        // TODO add your handling code here:
        jFramePengaturan_BagianTambahkanAdmin jFramePengaturan_BagianTambahkanAdmin = new jFramePengaturan_BagianTambahkanAdmin();
        jFramePengaturan_BagianTambahkanAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btinformasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btinformasi2ActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btinformasi2ActionPerformed

    private void btTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTentangActionPerformed
        // TODO add your handling code here:
        JTentang JTentang = new JTentang();
        JTentang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btTentangActionPerformed

    private void btReferensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReferensiActionPerformed
        // TODO add your handling code here:
        Jreferensi Jreferensi = new Jreferensi();
        Jreferensi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btReferensiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPengaturan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPengaturan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAdmin;
    private javax.swing.JLabel LPengaturan;
    private javax.swing.JButton btData;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btInformasi;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btPasien;
    private javax.swing.JButton btReferensi;
    private javax.swing.JButton btSetting;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btTentang;
    private javax.swing.JButton btinformasi2;
    // End of variables declaration//GEN-END:variables
}
