/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doktergigi;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import static Doktergigi.Config.writeLog;


/**
 *
 * @author amaks
 */
public class jFrameDataPasien extends javax.swing.JFrame {
    private void load_table() {
    // Membuat model tabel
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("id_pasien");
    model.addColumn("Nama Pasien");
    model.addColumn("Usia");
    model.addColumn("Jenis Kelamin");
    model.addColumn("Berat Badan");
    model.addColumn("Tinggi Badan");
    model.addColumn("Nomor Telepon");
    model.addColumn("Praktek");
    model.addColumn("Keluhan");

    try {
         int no = 1;
        // Query untuk mendapatkan data dari database
        String sql = "SELECT * FROM t_pasien";
        java.sql.Connection conn = (Connection) Config.configDB();
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);

        // Menambahkan data ke model tabel
       
        while (res.next()) {
            model.addRow(new Object[]{
                res.getString(1),       // Nama pasien
                res.getString(2),             // Usia
                res.getString(3),     // Jenis kelamin
                res.getString(4),       // Berat badan
                res.getString(5),      // Tinggi badan
                res.getString(6),     // Nomor telepon
                res.getString(7),           // Praktek
                res.getString(8),         // Keluhan
                res.getString(9),         
                
                
            });
        }

        // Menampilkan data ke tabel
        tblDataPasien.setModel(model);

        writeLog("Data berhasil dimuat ke frame: " + getClass().getSimpleName());
    } catch (Exception e) {
        // Menangani error jika data tidak dapat ditampilkan
        JOptionPane.showMessageDialog(null, "Data tidak dapat ditampilkan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        writeLog("Data tidak dapat ditampilkan: " + e.getMessage());
    }
}


    /**
     * Creates new form jFrameDataPasien
     */
    public jFrameDataPasien() {
        initComponents();
        load_table();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btHome = new javax.swing.JButton();
        btPasien = new javax.swing.JButton();
        btPasien2 = new javax.swing.JButton();
        btInformasi1 = new javax.swing.JButton();
        btPengaturan = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataPasien = new javax.swing.JTable();
        btEdit = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHome.setContentAreaFilled(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 40));

        btPasien.setContentAreaFilled(false);
        btPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 30));

        btPasien2.setContentAreaFilled(false);
        btPasien2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasien2ActionPerformed(evt);
            }
        });
        getContentPane().add(btPasien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 40, 30));

        btInformasi1.setContentAreaFilled(false);
        btInformasi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasi1ActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 40, 30));

        btPengaturan.setContentAreaFilled(false);
        btPengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPengaturanActionPerformed(evt);
            }
        });
        getContentPane().add(btPengaturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        btKeluar.setContentAreaFilled(false);
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 40, 30));

        txtCari.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 270, 30));

        btCari.setContentAreaFilled(false);
        getContentPane().add(btCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, 30, 30));

        tblDataPasien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDataPasien);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 610, 260));

        btEdit.setContentAreaFilled(false);
        getContentPane().add(btEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 370, 50, 30));

        btHapus.setContentAreaFilled(false);
        getContentPane().add(btHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 370, 50, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Background_DataPasien.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(734, 418));
        jLabel1.setMinimumSize(new java.awt.Dimension(734, 418));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        jFrameDashboard jFrameDashboard = new jFrameDashboard();
        jFrameDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasienActionPerformed
        // TODO add your handling code here:
        jFrameDataPasien jFrameDataPasien = new jFrameDataPasien();
        jFrameDataPasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPasienActionPerformed

    private void btPasien2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasien2ActionPerformed
        // TODO add your handling code here:
        jFramePasien jFramePasien = new jFramePasien();
        jFramePasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPasien2ActionPerformed

    private void btInformasi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasi1ActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btInformasi1ActionPerformed

    private void btPengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPengaturanActionPerformed
        // TODO add your handling code here:
        FPengaturan FPengaturan = new FPengaturan();
        FPengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPengaturanActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        FLogin FLogin = new FLogin();
        FLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameDataPasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameDataPasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCari;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btInformasi1;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btPasien;
    private javax.swing.JButton btPasien2;
    private javax.swing.JButton btPengaturan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataPasien;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
