/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doktergigi;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import static Doktergigi.Config.writeLog;
import javax.swing.JOptionPane;

/**
 *
 * @author amaks
 */
public class jFramePasien extends javax.swing.JFrame {

    /**
     * Creates new form jFramePasien
     */
    public jFramePasien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btHome = new javax.swing.JButton();
        btDataPasien = new javax.swing.JButton();
        btPasien = new javax.swing.JButton();
        btInformasi = new javax.swing.JButton();
        btPenganturan = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        txtNamaPasien = new javax.swing.JTextField();
        txtUsia = new javax.swing.JTextField();
        rbLakiLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        txtBeratBadan = new javax.swing.JTextField();
        txtTinggiBadan = new javax.swing.JTextField();
        txtNomorTelepon = new javax.swing.JTextField();
        cbPraktek = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtKeluhan = new javax.swing.JTextArea();
        btSimpan = new javax.swing.JButton();
        btReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHome.setContentAreaFilled(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 30));

        btDataPasien.setContentAreaFilled(false);
        btDataPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btDataPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 30));

        btPasien.setContentAreaFilled(false);
        btPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 40));

        btInformasi.setContentAreaFilled(false);
        btInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasiActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 40));

        btPenganturan.setContentAreaFilled(false);
        btPenganturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPenganturanActionPerformed(evt);
            }
        });
        getContentPane().add(btPenganturan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        btKeluar.setContentAreaFilled(false);
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 40, 40));
        getContentPane().add(txtNamaPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 65, 230, -1));
        getContentPane().add(txtUsia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 94, 70, -1));

        buttonGroup1.add(rbLakiLaki);
        rbLakiLaki.setForeground(new java.awt.Color(255, 255, 255));
        rbLakiLaki.setText("Laki - Laki");
        getContentPane().add(rbLakiLaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        buttonGroup1.add(rbPerempuan);
        rbPerempuan.setForeground(new java.awt.Color(255, 255, 255));
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));
        getContentPane().add(txtBeratBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 145, 90, -1));
        getContentPane().add(txtTinggiBadan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 175, 90, -1));
        getContentPane().add(txtNomorTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 205, 210, -1));

        cbPraktek.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Konsultasi", "Konsultasi + Tindakan" }));
        getContentPane().add(cbPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, -1));

        txtKeluhan.setColumns(20);
        txtKeluhan.setRows(5);
        jScrollPane1.setViewportView(txtKeluhan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 340, 70));

        btSimpan.setContentAreaFilled(false);
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 50, 30));

        btReset.setContentAreaFilled(false);
        getContentPane().add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 60, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Background_Pasien.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        jFrameDashboard jFrameDashboard = new jFrameDashboard();
        jFrameDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btDataPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataPasienActionPerformed
        // TODO add your handling code here:
        jFrameDataPasien jFrameDataPasien = new jFrameDataPasien();
        jFrameDataPasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDataPasienActionPerformed

    private void btPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasienActionPerformed
        // TODO add your handling code here:
        jFramePasien jFramePasien = new jFramePasien();
        jFramePasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPasienActionPerformed

    private void btInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasiActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btInformasiActionPerformed

    private void btPenganturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPenganturanActionPerformed
        // TODO add your handling code here:
        FPengaturan FPengaturan = new FPengaturan();
        FPengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPenganturanActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        FLogin FLogin = new FLogin();
        FLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        // TODO add your handling code here:
        try {
        // Mendapatkan data jenis kelamin dari radio button
        String jenisKelamin = "";
        if (rbLakiLaki.isSelected()) {
            jenisKelamin = "Laki-Laki";
        } else if (rbPerempuan.isSelected()) {
            jenisKelamin = "Perempuan";
        }

        // Validasi input wajib diisi
        if (txtNamaPasien.getText().isEmpty() || txtUsia.getText().isEmpty() ||
            jenisKelamin.isEmpty() || txtBeratBadan.getText().isEmpty() ||
            txtTinggiBadan.getText().isEmpty() || txtNomorTelepon.getText().isEmpty() ||
            cbPraktek.getSelectedIndex() == 0 || txtKeluhan.getText().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua data!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Query SQL untuk menyisipkan data ke tabel t_pasien
        String sql = "INSERT INTO t_pasien (nama_pasien, usia, jenis_kelamin, berat_badan, tinggi_badan, nomor_telepon, praktek, keluhan) "
                   + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";
        
        // Membuat koneksi ke database
        java.sql.Connection conn = (Connection) Config.configDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        // Set nilai parameter query
        pst.setString(1, txtNamaPasien.getText());           // nama_pasien
        pst.setString(2, txtUsia.getText());                 // usia
        pst.setString(3, jenisKelamin);                      // jenis_kelamin
        pst.setString(4, txtBeratBadan.getText());           // berat_badan
        pst.setString(5, txtTinggiBadan.getText());          // tinggi_badan
        pst.setString(6, txtNomorTelepon.getText());         // nomor_telepon
        pst.setString(7, cbPraktek.getSelectedItem().toString()); // praktek
        pst.setString(8, txtKeluhan.getText());              // keluhan dari JTextArea

        // Eksekusi query
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");

        // Log informasi keberhasilan
        writeLog("Penyimpanan Data Berhasil untuk pasien: " + txtNamaPasien.getText());

        // Membersihkan input form
        bersihkan();
    } catch (Exception e) {
        // Menampilkan pesan error jika ada kesalahan
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Kesalahan", JOptionPane.ERROR_MESSAGE);
        writeLog("Data gagal disimpan: " + e.getMessage());
    }
    }//GEN-LAST:event_btSimpanActionPerformed
private void bersihkan() {
    txtNamaPasien.setText("");
    txtUsia.setText("");
    buttonGroup1.clearSelection(); // Menghapus pilihan pada radio button
    txtBeratBadan.setText("");
    txtTinggiBadan.setText("");
    txtNomorTelepon.setText("");
    cbPraktek.setSelectedIndex(0);
    txtKeluhan.setText("");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePasien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePasien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDataPasien;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btInformasi;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btPasien;
    private javax.swing.JButton btPenganturan;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSimpan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbPraktek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rbLakiLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField txtBeratBadan;
    private javax.swing.JTextArea txtKeluhan;
    private javax.swing.JTextField txtNamaPasien;
    private javax.swing.JTextField txtNomorTelepon;
    private javax.swing.JTextField txtTinggiBadan;
    private javax.swing.JTextField txtUsia;
    // End of variables declaration//GEN-END:variables
}
