/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doktergigi;

/**
 *
 * @author amaks
 */
public class jFrameDashboard extends javax.swing.JFrame {

    /**
     * Creates new form jFrameDashboard
     */
    public jFrameDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btHome = new javax.swing.JButton();
        btData = new javax.swing.JButton();
        btPasien1 = new javax.swing.JButton();
        btInformasi = new javax.swing.JButton();
        btSetting = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        btPasien2 = new javax.swing.JButton();
        btKonsultasi = new javax.swing.JButton();
        btPraktek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLaporan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btHome.setContentAreaFilled(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 40));

        btData.setContentAreaFilled(false);
        btData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataActionPerformed(evt);
            }
        });
        getContentPane().add(btData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 30));

        btPasien1.setContentAreaFilled(false);
        btPasien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasien1ActionPerformed(evt);
            }
        });
        getContentPane().add(btPasien1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 30));

        btInformasi.setContentAreaFilled(false);
        btInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasiActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 40));

        btSetting.setContentAreaFilled(false);
        btSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingActionPerformed(evt);
            }
        });
        getContentPane().add(btSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 50, 40));

        btKeluar.setContentAreaFilled(false);
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 40, 40));

        btPasien2.setContentAreaFilled(false);
        getContentPane().add(btPasien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 40, 30));

        btKonsultasi.setContentAreaFilled(false);
        getContentPane().add(btKonsultasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 40, 30));

        btPraktek.setContentAreaFilled(false);
        getContentPane().add(btPraktek, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 40, 30));

        tblLaporan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblLaporan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 320, 480, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Background_Dashboard.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        jFrameDashboard jFrameDashboard = new jFrameDashboard();
        jFrameDashboard.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btHomeActionPerformed

    private void btDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataActionPerformed
        // TODO add your handling code here:
        jFrameDataPasien jFrameDataPasien = new jFrameDataPasien();
        jFrameDataPasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDataActionPerformed

    private void btPasien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasien1ActionPerformed
        // TODO add your handling code here:
        jFramePasien jFramePasien = new jFramePasien();
        jFramePasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPasien1ActionPerformed

    private void btInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasiActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btInformasiActionPerformed

    private void btSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingActionPerformed
        // TODO add your handling code here:
        FPengaturan FPengaturan = new FPengaturan();
        FPengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSettingActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        FLogin FLogin = new FLogin();
        FLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btData;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btInformasi;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btKonsultasi;
    private javax.swing.JButton btPasien1;
    private javax.swing.JButton btPasien2;
    private javax.swing.JButton btPraktek;
    private javax.swing.JButton btSetting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLaporan;
    // End of variables declaration//GEN-END:variables
}
