/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Doktergigi;

/**
 *
 * @author amaks
 */
public class Jreferensi extends javax.swing.JFrame {

    /**
     * Creates new form Jreferensi
     */
    public Jreferensi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btReferensi = new javax.swing.JButton();
        btTentang = new javax.swing.JButton();
        btInformasi2 = new javax.swing.JButton();
        btHome = new javax.swing.JButton();
        btData = new javax.swing.JButton();
        btPasien = new javax.swing.JButton();
        btInformasi = new javax.swing.JButton();
        btSetting = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        jBackground_refrensi = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btReferensi.setContentAreaFilled(false);
        btReferensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btReferensiActionPerformed(evt);
            }
        });
        getContentPane().add(btReferensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 100, 40));

        btTentang.setContentAreaFilled(false);
        btTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTentangActionPerformed(evt);
            }
        });
        getContentPane().add(btTentang, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 110, 40));

        btInformasi2.setContentAreaFilled(false);
        btInformasi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasi2ActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(416, 0, 100, 40));

        btHome.setContentAreaFilled(false);
        btHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 40));

        btData.setContentAreaFilled(false);
        btData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDataActionPerformed(evt);
            }
        });
        getContentPane().add(btData, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 40, 30));

        btPasien.setContentAreaFilled(false);
        btPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPasienActionPerformed(evt);
            }
        });
        getContentPane().add(btPasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 40, 40));

        btInformasi.setContentAreaFilled(false);
        btInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInformasiActionPerformed(evt);
            }
        });
        getContentPane().add(btInformasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 40, 40));

        btSetting.setContentAreaFilled(false);
        btSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSettingActionPerformed(evt);
            }
        });
        getContentPane().add(btSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 40, 30));

        btKeluar.setContentAreaFilled(false);
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 347, 40, 40));

        jBackground_refrensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/fRefensi_background.png"))); // NOI18N
        jBackground_refrensi.setText("jLabel1");
        getContentPane().add(jBackground_refrensi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHomeActionPerformed
        // TODO add your handling code here:
        jFrameDashboard jFrameDashboard = new jFrameDashboard();
        jFrameDashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btHomeActionPerformed

    private void btDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDataActionPerformed
        // TODO add your handling code here:
        jFrameDataPasien jFrameDataPasien = new jFrameDataPasien();
        jFrameDataPasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btDataActionPerformed

    private void btPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPasienActionPerformed
        // TODO add your handling code here:
        jFramePasien jFramePasien = new jFramePasien();
        jFramePasien.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btPasienActionPerformed

    private void btInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasiActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btInformasiActionPerformed

    private void btSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSettingActionPerformed
        // TODO add your handling code here:
        FPengaturan FPengaturan = new FPengaturan();
        FPengaturan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btSettingActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        // TODO add your handling code here:
        FLogin FLogin = new FLogin();
        FLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btReferensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btReferensiActionPerformed
        // TODO add your handling code here:
        Jreferensi Jreferensi = new Jreferensi();
        Jreferensi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btReferensiActionPerformed

    private void btTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTentangActionPerformed
        // TODO add your handling code here:
        JTentang JTentang = new JTentang();
        JTentang.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btTentangActionPerformed

    private void btInformasi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInformasi2ActionPerformed
        // TODO add your handling code here:
        FInfo FInfo = new FInfo();
        FInfo.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btInformasi2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jreferensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jreferensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jreferensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jreferensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jreferensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btData;
    private javax.swing.JButton btHome;
    private javax.swing.JButton btInformasi;
    private javax.swing.JButton btInformasi2;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btPasien;
    private javax.swing.JButton btReferensi;
    private javax.swing.JButton btSetting;
    private javax.swing.JButton btTentang;
    private javax.swing.JLabel jBackground_refrensi;
    // End of variables declaration//GEN-END:variables
}
